### PR TITLE
fixing build for windows

### PR DESCRIPTION
**Pull request by CitroenGames**
adding iostream for std::cout

### CODE REVIEW

**Comment by Hatrickek** [comment]
It's interesting that this is not necessary in action container builds. Are you using MSVC?

**Comment by CitroenGames** [comment]
i used cmake and visual studio to compile here is what the error looks like. 1 thing to note is you must delete the build folder of cmake to get this error.
image

**Comment by Hatrickek** [comment]
That line only compiles when Jolt asserts are enabled. Somehow they were disabled in the first place so it didn't error out.

Could you change that line to this instead so I can merge this:
```cpp 
OX_CORE_FATAL("{0}:{1}:{2} {3}", inFile, inLine, inExpression, inMessage != nullptr ? inMessage : "");
```

**Comment by CitroenGames** [comment]
so i should remove the iostream include and replace the cout line with this?:
`#ifdef JPH_ENABLE_ASSERTS
  static bool AssertFailedImpl(const char* inExpression, const char* inMessage, const char* inFile, JPH::uint inLine) {
    OX_CORE_FATAL("{0}:{1}:{2} {3}", inFile, inLine, inExpression, inMessage != nullptr ? inMessage : "");
    return true;
  };
#endif
`

**Comment by Hatrickek** [comment]
Yes.

**Comment by CitroenGames** [comment]
Done i updated the branch!

**Comment by Hatrickek** [comment]
Thanks 👍

**Pull request merged**
